CREATE TABLE orders (
 id SERIAL PRIMARY KEY,
 customer_name VARCHAR(255) NOT NULL,
 created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 product_name VARCHAR(255) NOT NULL,
 quantity INT DEFAULT 0
);
